src/plugins/SasBlogModule/src/Controller/BlogController.php
<?php declare(strict_types=1);

namespace Sas\BlogModule\Controller;

use Sas\BlogModule\Page\Blog\BlogPageLoader;
use Shopware\Core\System\SalesChannel\SalesChannelContext;
use Shopware\Storefront\Controller\StorefrontController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Blog detail page controller
 *
 * @Route(defaults={"_routeScope"={"storefront"}})
 */
class BlogController extends StorefrontController
{
    private BlogPageLoader $blogPageLoader;

    public function __construct(BlogPageLoader $blogPageLoader)
    {
        $this->blogPageLoader = $blogPageLoader;
    }

    /**
     * @Route("/sas_blog/{articleId}", name="sas.frontend.blog.detail", methods={"GET"})
     */
    public function detailAction(Request $request, SalesChannelContext $context): Response
    {
        $page = $this->blogPageLoader->load($request, $context);

        return $this->renderStorefront('@Storefront/storefront/page/content/index.html.twig', ['page' => $page]);
    }
}

src/plugins/SasBlogModule/src/Controller/StoreApi/BlogController.php
<?php declare(strict_types=1);

namespace Sas\BlogModule\Controller\StoreApi;

use OpenApi\Annotations as OA;
use Shopware\Core\Framework\DataAbstractionLayer\EntityRepository;
use Shopware\Core\Framework\DataAbstractionLayer\Search\Criteria;
use Shopware\Core\Framework\DataAbstractionLayer\Search\Filter\EqualsFilter;
use Shopware\Core\Framework\Plugin\Exception\DecorationPatternException;
use Shopware\Core\Framework\Uuid\Uuid;
use Shopware\Core\System\SalesChannel\SalesChannelContext;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route(defaults={"_routeScope"={"store-api"}})
 */
class BlogController extends AbstractBlogController
{
    /**
     * @var EntityRepository
     */
    private $blogRepository;

    public function __construct(EntityRepository $blogRepository)
    {
        $this->blogRepository = $blogRepository;
    }

    public function getDecorated(): AbstractBlogController
    {
        throw new DecorationPatternException(self::class);
    }

    /**
     * @OA\Get(
     *      path="/store-api/blog",
     *      summary="This route can be used to load the sas_blog_entries by specific filters",
     *      operationId="listBlog",
     *      tags={"Store API", "Blog"},
     *      @OA\Parameter(name="Api-Basic-Parameters"),
     *      @OA\Response(
     *          response="200",
     *          description="",
     *          @OA\JsonContent(type="object",
     *              @OA\Property(
     *                  property="total",
     *                  type="integer",
     *                  description="Total amount"
     *              ),
     *              @OA\Property(
     *                  property="aggregations",
     *                  type="object",
     *                  description="aggregation result"
     *              ),
     *              @OA\Property(
     *                  property="elements",
     *                  type="array",
     *                  @OA\Items(ref="#/components/schemas/blog_entities_flat")
     *              )
     *          )
     *     )
     * )
     * @Route("/store-api/blog", name="store-api.sas.blog.load", methods={"GET","POST"}, defaults={"_entity"="sas_blog_entries"})
     */
    public function load(Request $request, Criteria $criteria, SalesChannelContext $context): BlogControllerResponse
    {
        $criteria = $this->buildCriteria($request, $criteria);

        return new BlogControllerResponse($this->blogRepository->search($criteria, $context->getContext()));
    }

    protected function buildCriteria(Request $request, Criteria $criteria): Criteria
    {
        $search = $request->get('search');
        if ($search) {
            if (Uuid::isValid($search)) {
                $criteria->setIds([$search]);
            } else {
                $criteria->addFilter(new EqualsFilter('slug', $search));
            }
        }

        $criteria->addAssociations(['blogAuthor.salutation', 'blogCategories']);

        return $criteria;
    }
}

src/plugins/SasBlogModule/src/Controller/StoreApi/BlogControllerResponse.php
<?php declare(strict_types=1);

namespace Sas\BlogModule\Controller\StoreApi;

use Sas\BlogModule\Content\Blog\BlogEntriesCollection;
use Shopware\Core\Framework\DataAbstractionLayer\Search\EntitySearchResult;
use Shopware\Core\System\SalesChannel\StoreApiResponse;

class BlogControllerResponse extends StoreApiResponse
{
    /**
     * @var EntitySearchResult
     */
    protected $object;

    public function __construct(EntitySearchResult $object)
    {
        parent::__construct($object);
    }

    public function getBlogEntries(): BlogEntriesCollection
    {
        /** @var BlogEntriesCollection $collection */
        $collection = $this->object->getEntities();

        return $collection;
    }
}

src/plugins/SasBlogModule/src/Resources/views/storefront/component/blog/card/box.html.twig
{% block sas_blog_card %}
    <article class="card blog-card gp-article">
        {% block sas_blog_card_teaser_image %}
            <a href="{{ seoUrl('sas.frontend.blog.detail', {'articleId': article.id}) }}"
                   title="{{ article.translated.title }}"
                   class="blog-image-link">
                    {% if article.media.url %}
                        {% set attributes = {
                            'class': 'blog-image card-img-top',
                            'alt': (article.media.translated.alt ?: article.media.fileName),
                            'title': (article.media.translated.title ?: article.media.fileName)
                        } %}

                        {% sw_thumbnails 'blog-image-thumbnails' with {
                            media: article.media,
                            sizes: {
                                'xs': '330px',
                                'sm': '650px',
                                'md': '650px',
                                'lg': '650px',
                                'xl': '900px',
                            }
                        } %}
                    {% else %}
                        <div class="blog-image-placeholder">
                            {% sw_icon 'placeholder' style {
                                'size': 'fluid'
                            } %}
                        </div>
                    {% endif %}
                </a>
        {% endblock %}
        {% block sas_blog_card_body %}
            <div class="card-body">
                <div class="d-flex flex-column">
                    {% block sas_blog_card_title_date %}
                        <p class="mt-2 mb-1 d-flex align-items-center blog-date">
                            <small>{{ article.publishedAt|format_date('short', locale=app.request.locale) }}</small>
                        </p>
                    {% endblock %}
                    {% block sas_blog_card_title %}
                        <h2 class="card-title mt-0 blog-title">
                            {% block sas_blog_card_title_link %}
                                <a href="{{ seoUrl('sas.frontend.blog.detail', { articleId: article.id }) }}"
                                   title="{{ article.translated.title }}"
                                   class="text-decoration-none">
                                    {{ article.translated.title }}
                                </a>
                            {% endblock %}
                        </h2>
                    {% endblock %}
                </div>
                {% block sas_blog_card_teaser %}
                    <p class="card-text font-size-small mb-0">{{ article.translated.teaser }}</p>
                {% endblock %}
								<a class="gp-article__link" href="{{ seoUrl('sas.frontend.blog.detail', {'articleId': article.id}) }}">view more</a>
            </div>
        {% endblock %}

        {% block sas_blog_card_footer %}
        <div class="card-footer text-muted">
            {% block sas_blog_card_footer_author %}
                {% if config('SasBlogModule').config.showAuthor %}
                    {% if article.blogAuthor.media.url %}
                        {% set attributes = {
                            'class': 'blog-author-avatar',
                            'alt': (article.blogAuthor.media.translated.alt ?: article.blogAuthor.media.fileName),
                            'title': (article.blogAuthor.media.translated.title ?: article.blogAuthor.media.fileName)
                        } %}

                        {% sw_thumbnails 'blog-author-avatar-thumbnails' with {
                            media: article.blogAuthor.media,
                            sizes: {
                            'xs': '80px'
                        }
                            } %}
                    {% else %}
                        <div class="blog-image-placeholder">
                            {% sw_icon 'placeholder' style {
                                'size': 'fluid'
                                } %}
                        </div>
                    {% endif %}
                    <p class="blog-author-display-name">{{ article.blogAuthor.displayName }}<br>
                        <small class="text-muted">{{ article.blogAuthor.blogEntries|length }} {{ 'sas-blog.box.author.countEntries'|trans|sw_sanitize }}</small>
                    </p>
                {% endif %}
            {% endblock %}
        </div>
        {% endblock %}
    </article>
{% endblock %}